# Долбоордун тиркемелер, база, авторизация, Google OAuth жана статикалык файл жөндөөлөрүнө жооп берет.
"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# Импортирует инструменты для работы с системными путями.
import os
# Импортирует удобный объект Path для построения путей проекта.
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Определяет корневую папку Django-проекта.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Секретный ключ используется Django для подписи защищённых данных.
SECRET_KEY = 'django-insecure-kz&&^a+v6qn6#9#+f80=uj9wm8#x^k%&4po*z5x%s-dqb38yd%'

# SECURITY WARNING: don't run with debug turned on in production!
# Включает подробные сообщения об ошибках во время разработки.
DEBUG = True

# Перечисляет домены, с которых разрешено открывать сайт.
ALLOWED_HOSTS = []


# Application definition

# Регистрирует встроенные и сторонние приложения проекта.
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'app',
    'rest_framework',

]

SITE_ID = 2

# Задаёт последовательность обработчиков каждого HTTP-запроса и ответа.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
]

# Указывает главный файл URL-маршрутов проекта.
ROOT_URLCONF = 'books.urls'

# Настраивает движок шаблонов и доступные переменные контекста.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Указывает WSGI-приложение для запуска на веб-сервере.
WSGI_APPLICATION = 'books.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Настраивает локальную базу данных SQLite.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Подключает стандартные правила проверки надёжности паролей.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Устанавливает русский язык интерфейса Django.
LANGUAGE_CODE = 'ru'

# Устанавливает часовой пояс Бишкека.
TIME_ZONE = 'Asia/Bishkek'

# Включает систему переводов Django.
USE_I18N = True

# Сохраняет время в базе данных с учётом часовых поясов.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ========== МЕДИАФАЙЛЫ (для изображений) ==========
# Задаёт URL-префикс и папку для загруженных пользователями файлов.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ========== СТАТИЧЕСКИЕ ФАЙЛЫ ==========
# Задаёт адреса исходных и собранных CSS, JavaScript и других статических файлов.
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Настраивает страницы входа, выхода и перенаправления после авторизации.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
# Завершает пользовательскую сессию после закрытия браузера.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'prompt': 'select_account',
            'hl': 'ru',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
}

SOCIALACCOUNT_LOGIN_ON_GET = True
